create extension if not exists pgcrypto;

create table if not exists companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  company_id uuid references companies(id) on delete set null,
  full_name text,
  role text not null default 'owner',
  created_at timestamptz not null default now()
);

create table if not exists projects (
  id bigint generated by default as identity primary key,
  company_id uuid not null references companies(id) on delete cascade,
  name text not null,
  address text,
  status text not null default 'planning',
  start_date date,
  total_budget numeric(12,2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists owners (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  name text not null,
  contribution_amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists cost_categories (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  phase text not null check (phase in ('development', 'construction')),
  name text not null,
  budgeted_amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists vendors (
  id bigint generated by default as identity primary key,
  company_id uuid not null references companies(id) on delete cascade,
  name text not null,
  trade text,
  contact_email text,
  contact_phone text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists invoices (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  vendor_id bigint references vendors(id) on delete set null,
  category_id bigint references cost_categories(id) on delete set null,
  invoice_number text not null,
  amount numeric(12,2) not null default 0,
  invoice_date date,
  due_date date,
  status text not null default 'pending' check (status in ('pending', 'paid', 'disputed')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  company_id uuid not null references companies(id) on delete cascade,
  project_id bigint not null references projects(id) on delete cascade,
  category_id bigint references cost_categories(id) on delete set null,
  date date not null,
  description text not null,
  amount numeric(12,2) not null default 0,
  source text not null check (source in ('bank_import', 'manual')),
  matched_invoice_id bigint references invoices(id) on delete set null,
  raw_import_row jsonb,
  created_at timestamptz not null default now()
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references invoices(id) on delete cascade,
  transaction_id bigint references transactions(id) on delete set null,
  amount numeric(12,2) not null default 0,
  date date not null,
  created_at timestamptz not null default now()
);

-- Every edit and soft delete is an insert. Existing versions remain immutable.
create table if not exists cost_versions (
  id bigint generated by default as identity primary key,
  cost_id uuid not null,
  project_id bigint not null references projects(id) on delete cascade,
  owner_id bigint references owners(id) on delete set null,
  version integer not null check (version > 0),
  name text not null,
  amount numeric(12,2) not null default 0,
  phase text not null check (phase in ('development', 'construction')),
  cost_date date not null,
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  unique (cost_id, version)
);

create table if not exists review_items (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  owner_id bigint references owners(id) on delete set null,
  category_id bigint references cost_categories(id) on delete set null,
  source_name text,
  vendor text,
  amount numeric(12,2),
  transaction_date date,
  description text,
  entry_type text not null default 'unknown' check (entry_type in ('deposit', 'debit', 'unknown')),
  notes text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'removed')),
  raw_data jsonb,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

-- File bytes belong in Supabase Storage; this table retains their accounting metadata.
create table if not exists documents (
  id uuid primary key default gen_random_uuid(),
  project_id bigint not null references projects(id) on delete cascade,
  cost_id uuid,
  invoice_id bigint references invoices(id) on delete set null,
  review_item_id bigint references review_items(id) on delete set null,
  storage_bucket text not null,
  storage_path text not null,
  original_name text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  uploaded_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  unique (storage_bucket, storage_path)
);

create index if not exists projects_company_id_idx on projects(company_id);
create index if not exists owners_project_id_idx on owners(project_id);
create index if not exists cost_categories_project_id_idx on cost_categories(project_id);
create index if not exists vendors_company_id_idx on vendors(company_id);
create index if not exists invoices_project_id_idx on invoices(project_id);
create index if not exists transactions_project_id_idx on transactions(project_id);
create index if not exists payments_invoice_id_idx on payments(invoice_id);
create index if not exists cost_versions_project_id_idx on cost_versions(project_id);
create index if not exists cost_versions_latest_idx on cost_versions(cost_id, version desc);
create index if not exists review_items_project_status_idx on review_items(project_id, status);
create index if not exists documents_project_id_idx on documents(project_id);

create or replace view active_costs
with (security_invoker = true)
as
select latest.*
from (
  select distinct on (cost_id) *
  from cost_versions
  order by cost_id, version desc
) latest
where latest.deleted_at is null;

grant select on active_costs to authenticated;

create or replace function public.current_company_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select company_id from public.profiles where id = auth.uid()
$$;

revoke all on function public.current_company_id() from public;
grant execute on function public.current_company_id() to anon, authenticated;

alter table companies enable row level security;
alter table profiles enable row level security;
alter table projects enable row level security;
alter table owners enable row level security;
alter table cost_categories enable row level security;
alter table vendors enable row level security;
alter table invoices enable row level security;
alter table transactions enable row level security;
alter table payments enable row level security;
alter table cost_versions enable row level security;
alter table review_items enable row level security;
alter table documents enable row level security;

drop policy if exists companies_company_isolation on companies;
create policy companies_company_isolation on companies
  for select using (id = public.current_company_id());

drop policy if exists profiles_self_access on profiles;
create policy profiles_self_access on profiles
  for select using (id = auth.uid());

drop policy if exists projects_company_isolation on projects;
create policy projects_company_isolation on projects
  for all
  using (company_id = public.current_company_id())
  with check (company_id = public.current_company_id());

drop policy if exists owners_company_isolation on owners;
create policy owners_company_isolation on owners
  for all
  using (exists (
    select 1 from projects p
    where p.id = owners.project_id and p.company_id = public.current_company_id()
  ))
  with check (exists (
    select 1 from projects p
    where p.id = owners.project_id and p.company_id = public.current_company_id()
  ));

drop policy if exists categories_company_isolation on cost_categories;
create policy categories_company_isolation on cost_categories
  for all
  using (exists (
    select 1 from projects p
    where p.id = cost_categories.project_id and p.company_id = public.current_company_id()
  ))
  with check (exists (
    select 1 from projects p
    where p.id = cost_categories.project_id and p.company_id = public.current_company_id()
  ));

drop policy if exists vendors_company_isolation on vendors;
create policy vendors_company_isolation on vendors
  for all
  using (company_id = public.current_company_id())
  with check (company_id = public.current_company_id());

drop policy if exists invoices_company_isolation on invoices;
create policy invoices_company_isolation on invoices
  for all
  using (exists (
    select 1 from projects p
    where p.id = invoices.project_id and p.company_id = public.current_company_id()
  ))
  with check (exists (
    select 1 from projects p
    where p.id = invoices.project_id and p.company_id = public.current_company_id()
  ));

drop policy if exists transactions_company_isolation on transactions;
create policy transactions_company_isolation on transactions
  for all
  using (
    company_id = public.current_company_id()
    and exists (
      select 1 from projects p
      where p.id = transactions.project_id and p.company_id = public.current_company_id()
    )
  )
  with check (
    company_id = public.current_company_id()
    and exists (
      select 1 from projects p
      where p.id = transactions.project_id and p.company_id = public.current_company_id()
    )
  );

drop policy if exists payments_company_isolation on payments;
create policy payments_company_isolation on payments
  for all
  using (exists (
    select 1
    from invoices i
    join projects p on p.id = i.project_id
    where i.id = payments.invoice_id and p.company_id = public.current_company_id()
  ))
  with check (exists (
    select 1
    from invoices i
    join projects p on p.id = i.project_id
    where i.id = payments.invoice_id and p.company_id = public.current_company_id()
  ));

drop policy if exists cost_versions_company_isolation on cost_versions;
create policy cost_versions_company_isolation on cost_versions
  for select
  using (exists (
    select 1 from projects p
    where p.id = cost_versions.project_id and p.company_id = public.current_company_id()
  ));

drop policy if exists cost_versions_company_insert on cost_versions;
create policy cost_versions_company_insert on cost_versions
  for insert
  with check (exists (
    select 1 from projects p
    where p.id = cost_versions.project_id and p.company_id = public.current_company_id()
  ));

drop policy if exists review_items_company_isolation on review_items;
create policy review_items_company_isolation on review_items
  for all
  using (exists (
    select 1 from projects p
    where p.id = review_items.project_id and p.company_id = public.current_company_id()
  ))
  with check (exists (
    select 1 from projects p
    where p.id = review_items.project_id and p.company_id = public.current_company_id()
  ));

drop policy if exists documents_company_isolation on documents;
create policy documents_company_isolation on documents
  for all
  using (exists (
    select 1 from projects p
    where p.id = documents.project_id and p.company_id = public.current_company_id()
  ))
  with check (exists (
    select 1 from projects p
    where p.id = documents.project_id and p.company_id = public.current_company_id()
  ));
