create table if not exists public.project_financing_transactions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  entry_type text not null check (entry_type in ('loan_received', 'principal_repayment', 'interest_payment', 'owner_distribution')),
  entry_status text not null default 'completed' check (entry_status in ('planned', 'completed')),
  counterparty text not null check (length(trim(counterparty)) > 0),
  owner_id bigint references public.owners(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  entry_date date not null,
  payment_method text not null default '',
  reference text not null default '',
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_financing_transactions_project_date_idx
  on public.project_financing_transactions (project_id, entry_date desc, id desc);

create index if not exists project_financing_transactions_counterparty_idx
  on public.project_financing_transactions (project_id, lower(counterparty));

alter table public.project_financing_transactions enable row level security;

drop policy if exists project_financing_transactions_project_admin_access on public.project_financing_transactions;
create policy project_financing_transactions_project_admin_access on public.project_financing_transactions
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

grant select, insert, update, delete on public.project_financing_transactions to authenticated;
grant usage, select on sequence public.project_financing_transactions_id_seq to authenticated;
revoke all on public.project_financing_transactions from anon;
