-- Green Fort normalized project-cost ledger foundation.
-- Existing cost_versions remain the immutable source of truth; these fields add
-- separate cost-purpose and funding dimensions without changing old totals.

alter table public.owners
  add column if not exists ownership_percentage numeric(7,4),
  add column if not exists is_active boolean not null default true;

alter table public.cost_versions
  add column if not exists vendor_name text,
  add column if not exists main_category text,
  add column if not exists subcategory text,
  add column if not exists payer_type text,
  add column if not exists payer_owner_id bigint references public.owners(id) on delete set null,
  add column if not exists payer_name text,
  add column if not exists payment_source text,
  add column if not exists reference_number text,
  add column if not exists reimbursable boolean not null default false,
  add column if not exists loan_related boolean not null default false,
  add column if not exists notes text,
  add column if not exists recurring_frequency text,
  add column if not exists is_soft_cost_parent boolean not null default false;

alter table public.cost_versions drop constraint if exists cost_versions_payer_type_check;
alter table public.cost_versions add constraint cost_versions_payer_type_check
  check (payer_type is null or payer_type in ('owner', 'company', 'construction_loan', 'other_company', 'third_party'));
alter table public.cost_versions drop constraint if exists cost_versions_recurring_frequency_check;
alter table public.cost_versions add constraint cost_versions_recurring_frequency_check
  check (recurring_frequency is null or recurring_frequency in ('monthly', 'quarterly', 'annual'));

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  address text not null,
  parcel_number text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cost_subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.cost_categories(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  unique (category_id, name)
);

create table if not exists public.funding_sources (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  source_type text not null check (source_type in ('owner', 'company', 'construction_loan', 'other_company', 'third_party')),
  owner_id bigint references public.owners(id) on delete set null,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  funding_source_id bigint references public.funding_sources(id) on delete set null,
  lender_name text not null,
  loan_name text,
  account_last_four text,
  original_principal numeric(14,2),
  interest_rate numeric(9,6),
  start_date date,
  maturity_date date,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.transaction_allocations (
  id bigint generated by default as identity primary key,
  transaction_id bigint references public.transactions(id) on delete cascade,
  cost_id uuid,
  project_id bigint references public.projects(id) on delete cascade,
  allocation_percentage numeric(7,4),
  allocation_amount numeric(14,2) not null,
  created_at timestamptz not null default now(),
  check (allocation_percentage is null or allocation_percentage between 0 and 100),
  check (allocation_amount >= 0),
  check (transaction_id is not null or cost_id is not null)
);

create table if not exists public.ledger_audit_logs (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  cost_id uuid,
  action text not null check (action in ('create', 'update', 'archive', 'restore')),
  old_values jsonb,
  new_values jsonb,
  changed_by uuid references auth.users(id) on delete set null default auth.uid(),
  changed_at timestamptz not null default now()
);

create index if not exists cost_versions_project_main_category_idx on public.cost_versions(project_id, main_category);
create index if not exists cost_versions_project_payer_idx on public.cost_versions(project_id, payer_type, payer_owner_id);
create index if not exists funding_sources_project_idx on public.funding_sources(project_id);
create index if not exists loans_project_idx on public.loans(project_id);
create index if not exists transaction_allocations_project_idx on public.transaction_allocations(project_id);
create index if not exists ledger_audit_logs_cost_idx on public.ledger_audit_logs(project_id, cost_id, changed_at desc);

alter table public.properties enable row level security;
alter table public.cost_subcategories enable row level security;
alter table public.funding_sources enable row level security;
alter table public.loans enable row level security;
alter table public.transaction_allocations enable row level security;
alter table public.ledger_audit_logs enable row level security;

create policy properties_project_access on public.properties for all
  using (company_id = public.current_company_id() and (project_id is null or private.can_manage_project(project_id)))
  with check (company_id = public.current_company_id() and (project_id is null or private.can_manage_project(project_id)));
create policy subcategories_project_access on public.cost_subcategories for all
  using (exists (select 1 from public.cost_categories c where c.id = category_id and private.can_manage_project(c.project_id)))
  with check (exists (select 1 from public.cost_categories c where c.id = category_id and private.can_manage_project(c.project_id)));
create policy funding_sources_project_access on public.funding_sources for all
  using (private.can_manage_project(project_id)) with check (private.can_manage_project(project_id));
create policy loans_project_access on public.loans for all
  using (private.can_manage_project(project_id)) with check (private.can_manage_project(project_id));
create policy allocations_project_access on public.transaction_allocations for all
  using (private.can_manage_project(project_id)) with check (private.can_manage_project(project_id));
create policy ledger_audit_project_access on public.ledger_audit_logs for select
  using (private.can_manage_project(project_id));
create policy ledger_audit_project_insert on public.ledger_audit_logs for insert
  with check (private.can_manage_project(project_id));

grant select, insert, update, delete on public.properties, public.cost_subcategories,
  public.funding_sources, public.loans, public.transaction_allocations to authenticated;
grant select, insert on public.ledger_audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.create_cost_version_v8(
  p_project_id bigint, p_cost_id uuid, p_parent_cost_id uuid, p_owner_id bigint,
  p_name text, p_amount numeric, p_phase text, p_category text,
  p_lot_allocations jsonb, p_cost_date date, p_attachments jsonb default '[]'::jsonb,
  p_deleted boolean default false, p_details text default null,
  p_construction_draft_id uuid default null, p_payment_method text default null,
  p_payment_fee_percentage numeric default null, p_payment_fee_amount numeric default null,
  p_payment_date date default null, p_invoice_amount numeric default null,
  p_vendor_name text default null, p_main_category text default null,
  p_subcategory text default null, p_payer_type text default null,
  p_payer_owner_id bigint default null, p_payer_name text default null,
  p_payment_source text default null, p_reference_number text default null,
  p_reimbursable boolean default false, p_loan_related boolean default false,
  p_notes text default null, p_recurring_frequency text default null,
  p_is_soft_cost_parent boolean default false
) returns public.cost_versions
language plpgsql security invoker set search_path = '' as $$
declare
  next_version integer;
  allocation_total numeric;
  prior_row public.cost_versions;
  result public.cost_versions;
begin
  if not private.can_manage_project(p_project_id) then raise exception 'You do not have permission to manage this project'; end if;
  if p_amount < 0 then raise exception 'Amount cannot be negative'; end if;
  if p_payment_fee_percentage is not null and (p_payment_fee_percentage < 0 or p_payment_fee_percentage > 100) then raise exception 'Payment fee percentage must be between 0 and 100'; end if;
  if jsonb_typeof(coalesce(p_lot_allocations, '[]'::jsonb)) <> 'array' then raise exception 'Lot allocations must be an array'; end if;
  select coalesce(sum((item->>'amount')::numeric), 0) into allocation_total from jsonb_array_elements(coalesce(p_lot_allocations, '[]'::jsonb)) item;
  if jsonb_array_length(coalesce(p_lot_allocations, '[]'::jsonb)) > 0 and abs(allocation_total - p_amount) > 0.009 then raise exception 'Lot allocations must equal the total cost amount'; end if;
  if p_parent_cost_id is not null and not exists (select 1 from public.cost_versions where project_id = p_project_id and cost_id = p_parent_cost_id) then raise exception 'The parent cost does not exist in this project'; end if;

  perform pg_advisory_xact_lock(hashtextextended(p_cost_id::text, 0));
  select * into prior_row from public.cost_versions where project_id = p_project_id and cost_id = p_cost_id order by version desc limit 1;
  select coalesce(max(version), 0) + 1 into next_version from public.cost_versions where cost_id = p_cost_id and project_id = p_project_id;

  insert into public.cost_versions (
    cost_id, parent_cost_id, project_id, owner_id, version, name, details,
    construction_draft_id, payment_method, payment_fee_percentage, payment_fee_amount,
    payment_date, invoice_amount, amount, phase, category, lot_allocations, cost_date,
    attachments, deleted_at, vendor_name, main_category, subcategory, payer_type,
    payer_owner_id, payer_name, payment_source, reference_number, reimbursable,
    loan_related, notes, recurring_frequency, is_soft_cost_parent
  ) values (
    p_cost_id, p_parent_cost_id, p_project_id, p_owner_id, next_version, trim(p_name), nullif(trim(p_details), ''),
    p_construction_draft_id, nullif(trim(p_payment_method), ''), p_payment_fee_percentage, p_payment_fee_amount,
    p_payment_date, p_invoice_amount, p_amount, p_phase, nullif(trim(p_category), ''), coalesce(p_lot_allocations, '[]'::jsonb), p_cost_date,
    coalesce(p_attachments, '[]'::jsonb), case when p_deleted then now() else null end,
    nullif(trim(p_vendor_name), ''), nullif(trim(p_main_category), ''), nullif(trim(p_subcategory), ''), p_payer_type,
    p_payer_owner_id, nullif(trim(p_payer_name), ''), nullif(trim(p_payment_source), ''), nullif(trim(p_reference_number), ''),
    coalesce(p_reimbursable, false), coalesce(p_loan_related, false), nullif(trim(p_notes), ''), p_recurring_frequency,
    coalesce(p_is_soft_cost_parent, false)
  ) returning * into result;

  insert into public.ledger_audit_logs(project_id, cost_id, action, old_values, new_values)
  values (p_project_id, p_cost_id,
    case when p_deleted then 'archive' when prior_row.id is null then 'create' else 'update' end,
    case when prior_row.id is null then null else to_jsonb(prior_row) end, to_jsonb(result));
  return result;
end;
$$;

grant execute on function public.create_cost_version_v8(bigint, uuid, uuid, bigint, text, numeric, text, text, jsonb, date, jsonb, boolean, text, uuid, text, numeric, numeric, date, numeric, text, text, text, text, bigint, text, text, text, boolean, boolean, text, text, boolean) to authenticated;
revoke all on function public.create_cost_version_v8(bigint, uuid, uuid, bigint, text, numeric, text, text, jsonb, date, jsonb, boolean, text, uuid, text, numeric, numeric, date, numeric, text, text, text, text, bigint, text, text, text, boolean, boolean, text, text, boolean) from public, anon;
