create extension if not exists pgcrypto;

create table if not exists public.cost_versions (
  id bigint generated by default as identity primary key,
  cost_id uuid not null,
  project_id bigint not null references public.projects(id) on delete cascade,
  owner_id bigint references public.owners(id) on delete set null,
  version integer not null check (version > 0),
  name text not null,
  amount numeric(12,2) not null check (amount > 0),
  phase text not null check (phase in ('development', 'construction')),
  cost_date date not null,
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  unique (cost_id, version)
);

create table if not exists public.incomes (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  description text not null,
  source text not null,
  amount numeric(12,2) not null check (amount > 0),
  income_date date not null,
  income_type text not null default 'project_income'
    check (income_type in ('project_income', 'refund', 'reimbursement', 'other')),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_items (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  owner_id bigint references public.owners(id) on delete set null,
  category_id bigint references public.cost_categories(id) on delete set null,
  source_name text,
  vendor text,
  amount numeric(12,2),
  transaction_date date,
  description text,
  entry_type text not null default 'unknown' check (entry_type in ('deposit', 'debit', 'unknown')),
  notes text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'removed')),
  raw_data jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  project_id bigint not null references public.projects(id) on delete cascade,
  cost_id uuid,
  invoice_id bigint references public.invoices(id) on delete set null,
  review_item_id bigint references public.review_items(id) on delete set null,
  storage_bucket text not null,
  storage_path text not null,
  original_name text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  uploaded_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  unique (storage_bucket, storage_path)
);

alter table public.invoices add column if not exists vendor_name text;
alter table public.invoices add column if not exists description text;
alter table public.invoices add column if not exists classification text;
alter table public.invoices add column if not exists source_name text;

create index if not exists cost_versions_project_id_idx on public.cost_versions(project_id);
create index if not exists cost_versions_latest_idx on public.cost_versions(cost_id, version desc);
create index if not exists incomes_project_active_idx on public.incomes(project_id) where deleted_at is null;
create index if not exists review_items_project_status_idx on public.review_items(project_id, status);
create index if not exists documents_project_id_idx on public.documents(project_id);

create or replace view public.active_costs
with (security_invoker = true)
as
select latest.*
from (
  select distinct on (cost_id) *
  from public.cost_versions
  order by cost_id, version desc
) latest
where latest.deleted_at is null;

create or replace function public.create_cost_version(
  p_project_id bigint,
  p_cost_id uuid,
  p_owner_id bigint,
  p_name text,
  p_amount numeric,
  p_phase text,
  p_cost_date date,
  p_attachments jsonb default '[]'::jsonb,
  p_deleted boolean default false
)
returns public.cost_versions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  next_version integer;
  result public.cost_versions;
begin
  if not private.can_manage_project(p_project_id) then
    raise exception 'You do not have permission to manage this project';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_cost_id::text, 0));
  select coalesce(max(version), 0) + 1 into next_version
  from public.cost_versions
  where cost_id = p_cost_id and project_id = p_project_id;

  insert into public.cost_versions (
    cost_id, project_id, owner_id, version, name, amount, phase,
    cost_date, attachments, deleted_at
  ) values (
    p_cost_id, p_project_id, p_owner_id, next_version, trim(p_name), p_amount,
    p_phase, p_cost_date, coalesce(p_attachments, '[]'::jsonb),
    case when p_deleted then now() else null end
  ) returning * into result;

  return result;
end;
$$;

create or replace function public.approve_review_item(p_item_id bigint, p_category_id bigint)
returns public.transactions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  item public.review_items;
  project_company_id uuid;
  result public.transactions;
begin
  select * into item from public.review_items where id = p_item_id for update;
  if item.id is null or item.status <> 'pending' then
    raise exception 'This review item is no longer pending';
  end if;
  if not private.can_manage_project(item.project_id) then
    raise exception 'You do not have permission to manage this project';
  end if;
  if not exists (
    select 1 from public.cost_categories c
    where c.id = p_category_id and c.project_id = item.project_id
  ) then
    raise exception 'Select a category from this project';
  end if;

  select company_id into project_company_id from public.projects where id = item.project_id;
  insert into public.transactions (
    company_id, project_id, category_id, date, description, amount,
    source, matched_invoice_id, raw_import_row
  ) values (
    project_company_id, item.project_id, p_category_id,
    coalesce(item.transaction_date, current_date),
    coalesce(nullif(item.description, ''), nullif(item.vendor, ''), nullif(item.source_name, ''), 'Reviewed document'),
    coalesce(item.amount, 0), 'manual', null,
    jsonb_build_object('reviewItemId', item.id, 'sourceName', item.source_name, 'vendor', item.vendor)
  ) returning * into result;

  update public.review_items
  set status = 'approved', category_id = p_category_id, reviewed_at = now(), reviewed_by = auth.uid()
  where id = item.id;

  return result;
end;
$$;

create or replace function private.seed_project_categories()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.cost_categories (project_id, phase, name, budgeted_amount)
  values
    (new.id, 'development', 'Development', 0),
    (new.id, 'construction', 'Construction', 0);
  return new;
end;
$$;

drop trigger if exists on_project_created_seed_categories on public.projects;
create trigger on_project_created_seed_categories
  after insert on public.projects
  for each row execute function private.seed_project_categories();

insert into public.cost_categories (project_id, phase, name, budgeted_amount)
select p.id, defaults.phase, defaults.name, 0
from public.projects p
cross join (values ('development', 'Development'), ('construction', 'Construction')) defaults(phase, name)
where not exists (
  select 1 from public.cost_categories c
  where c.project_id = p.id and c.phase = defaults.phase and lower(c.name) = lower(defaults.name)
);

alter table public.cost_versions enable row level security;
alter table public.incomes enable row level security;
alter table public.review_items enable row level security;
alter table public.documents enable row level security;

create policy cost_versions_project_admin_access on public.cost_versions
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy incomes_project_admin_access on public.incomes
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy review_items_project_admin_access on public.review_items
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy documents_project_admin_access on public.documents
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'accounting-documents', 'accounting-documents', false, 10485760,
  array['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy accounting_documents_select on storage.objects
  for select to authenticated
  using (
    bucket_id = 'accounting-documents'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and private.can_manage_project(((storage.foldername(name))[1])::bigint)
  );

create policy accounting_documents_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'accounting-documents'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and private.can_manage_project(((storage.foldername(name))[1])::bigint)
  );

create policy accounting_documents_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'accounting-documents'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and private.can_manage_project(((storage.foldername(name))[1])::bigint)
  )
  with check (
    bucket_id = 'accounting-documents'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and private.can_manage_project(((storage.foldername(name))[1])::bigint)
  );

create policy accounting_documents_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'accounting-documents'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and private.can_manage_project(((storage.foldername(name))[1])::bigint)
  );

grant select on public.active_costs to authenticated;
grant select, insert, update, delete on public.cost_versions, public.incomes,
  public.review_items, public.documents to authenticated;
grant execute on function public.create_cost_version(bigint, uuid, bigint, text, numeric, text, date, jsonb, boolean) to authenticated;
grant execute on function public.approve_review_item(bigint, bigint) to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on public.cost_versions, public.incomes, public.review_items, public.documents from anon;
revoke all on function public.create_cost_version(bigint, uuid, bigint, text, numeric, text, date, jsonb, boolean) from public, anon;
revoke all on function public.approve_review_item(bigint, bigint) from public, anon;
