create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  source_row_id text,
  bank text not null,
  owner text not null default 'Project / Unassigned',
  is_owner_contribution boolean not null default false,
  date date,
  description text not null,
  amount numeric(14,2) not null default 0,
  balance numeric(14,2),
  account text,
  source_name text,
  category text,
  phase text,
  vendor text,
  memo text,
  confidence text,
  transaction_type text,
  raw_description text,
  review_reasons jsonb not null default '[]'::jsonb,
  classification_status text not null default 'needs_review',
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (project_id, source_row_id)
);

create index if not exists bank_transactions_project_date_idx
  on public.bank_transactions (project_id, date);

alter table public.bank_transactions enable row level security;

create policy bank_transactions_project_admin_access on public.bank_transactions
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

grant select, insert, update, delete on public.bank_transactions to authenticated;
grant usage, select on sequence public.bank_transactions_id_seq to authenticated;
revoke all on public.bank_transactions from anon;
