create table if not exists public.project_lot_commitments (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  lot text not null check (lot in ('Lot 2', 'Lot 3', 'Lot 4')),
  address text not null default '',
  commitment_amount numeric(12,2) not null default 0 check (commitment_amount >= 0),
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, lot)
);

alter table public.project_lot_commitments enable row level security;

drop policy if exists project_lot_commitments_project_admin_access on public.project_lot_commitments;
create policy project_lot_commitments_project_admin_access on public.project_lot_commitments
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

grant select, insert, update on public.project_lot_commitments to authenticated;
revoke all on public.project_lot_commitments from anon;
