create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table if not exists public.admin_allowlist (
  email text primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

insert into public.admin_allowlist (email)
values ('mfuyar@gmail.com')
on conflict (email) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  is_global_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_key
  on public.profiles (lower(email));

create table if not exists public.project_members (
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'project_admin' check (role = 'project_admin'),
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.project_invitations (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  email text not null,
  role text not null default 'project_admin' check (role = 'project_admin'),
  invited_by uuid references auth.users(id) on delete set null default auth.uid(),
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists project_invitations_pending_key
  on public.project_invitations (project_id, lower(email))
  where accepted_at is null;

create or replace function private.is_global_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select p.is_global_admin
    from public.profiles p
    where p.id = p_user_id
  ), false)
$$;

create or replace function private.can_manage_project(p_project_id bigint, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_global_admin(p_user_id)
    or exists (
      select 1
      from public.project_members pm
      where pm.project_id = p_project_id
        and pm.user_id = p_user_id
        and pm.role = 'project_admin'
    )
$$;

create or replace function private.can_access_company(p_company_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_global_admin(p_user_id)
    or exists (
      select 1
      from public.project_members pm
      join public.projects p on p.id = pm.project_id
      where pm.user_id = p_user_id
        and p.company_id = p_company_id
    )
$$;

grant execute on function private.is_global_admin(uuid) to authenticated;
grant execute on function private.can_manage_project(bigint, uuid) to authenticated;
grant execute on function private.can_access_company(uuid, uuid) to authenticated;

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  global_access boolean;
begin
  global_access := exists (
    select 1 from public.admin_allowlist a where a.email = lower(new.email)
  );

  insert into public.profiles (id, email, full_name, is_global_admin)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    global_access
  )
  on conflict (id) do update
    set email = excluded.email,
        is_global_admin = excluded.is_global_admin;

  if global_access then
    insert into public.project_members (project_id, user_id, role)
    select p.id, new.id, 'project_admin'
    from public.projects p
    on conflict (project_id, user_id) do nothing;
  end if;

  insert into public.project_members (project_id, user_id, role)
  select i.project_id, new.id, i.role
  from public.project_invitations i
  where lower(i.email) = lower(new.email)
    and i.accepted_at is null
  on conflict (project_id, user_id) do nothing;

  update public.project_invitations
  set accepted_at = now()
  where lower(email) = lower(new.email)
    and accepted_at is null;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute function private.handle_new_auth_user();

create or replace function private.assign_project_creator()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is not null then
    insert into public.project_members (project_id, user_id, role)
    values (new.id, auth.uid(), 'project_admin')
    on conflict (project_id, user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists on_project_created_assign_admin on public.projects;
create trigger on_project_created_assign_admin
  after insert on public.projects
  for each row execute function private.assign_project_creator();

create or replace function public.assign_project_admin(p_project_id bigint, p_email text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(trim(p_email));
  target_user_id uuid;
begin
  if auth.uid() is null or not private.can_manage_project(p_project_id, auth.uid()) then
    raise exception 'You do not have permission to manage this project';
  end if;

  if normalized_email = '' or normalized_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Enter a valid administrator email';
  end if;

  select p.id into target_user_id
  from public.profiles p
  where lower(p.email) = normalized_email;

  if target_user_id is not null then
    insert into public.project_members (project_id, user_id, role)
    values (p_project_id, target_user_id, 'project_admin')
    on conflict (project_id, user_id) do update set role = excluded.role;
    return 'assigned';
  end if;

  insert into public.project_invitations (project_id, email, role, invited_by)
  values (p_project_id, normalized_email, 'project_admin', auth.uid())
  on conflict (project_id, lower(email)) where accepted_at is null
  do update set invited_by = excluded.invited_by;
  return 'invited';
end;
$$;

revoke all on function public.assign_project_admin(bigint, text) from public, anon;
grant execute on function public.assign_project_admin(bigint, text) to authenticated;

alter table public.admin_allowlist enable row level security;
alter table public.profiles enable row level security;
alter table public.project_members enable row level security;
alter table public.project_invitations enable row level security;
alter table public.companies enable row level security;
alter table public.projects enable row level security;
alter table public.owners enable row level security;
alter table public.cost_categories enable row level security;
alter table public.vendors enable row level security;
alter table public.invoices enable row level security;
alter table public.transactions enable row level security;
alter table public.payments enable row level security;

create policy admin_allowlist_global_admin on public.admin_allowlist
  for all to authenticated
  using (private.is_global_admin())
  with check (private.is_global_admin());

create policy profiles_authorized_select on public.profiles
  for select to authenticated
  using (
    id = auth.uid()
    or private.is_global_admin()
    or exists (
      select 1 from public.project_members mine
      join public.project_members theirs on theirs.project_id = mine.project_id
      where mine.user_id = auth.uid() and theirs.user_id = profiles.id
    )
  );

create policy profiles_global_admin_update on public.profiles
  for update to authenticated
  using (private.is_global_admin())
  with check (private.is_global_admin());

create policy project_members_authorized_select on public.project_members
  for select to authenticated
  using (user_id = auth.uid() or private.can_manage_project(project_id));

create policy project_members_admin_insert on public.project_members
  for insert to authenticated
  with check (private.can_manage_project(project_id));

create policy project_members_admin_update on public.project_members
  for update to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy project_members_admin_delete on public.project_members
  for delete to authenticated
  using (private.can_manage_project(project_id));

create policy project_invitations_admin_access on public.project_invitations
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy companies_authorized_select on public.companies
  for select to authenticated
  using (private.can_access_company(id));

create policy companies_global_admin_write on public.companies
  for all to authenticated
  using (private.is_global_admin())
  with check (private.is_global_admin());

create policy projects_authorized_select on public.projects
  for select to authenticated
  using (private.can_manage_project(id));

create policy projects_authorized_update on public.projects
  for update to authenticated
  using (private.can_manage_project(id))
  with check (private.can_manage_project(id));

create policy projects_authorized_delete on public.projects
  for delete to authenticated
  using (private.can_manage_project(id));

create policy projects_global_admin_insert on public.projects
  for insert to authenticated
  with check (private.is_global_admin());

create policy owners_project_admin_access on public.owners
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy categories_project_admin_access on public.cost_categories
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy vendors_company_admin_access on public.vendors
  for all to authenticated
  using (private.can_access_company(company_id))
  with check (private.can_access_company(company_id));

create policy invoices_project_admin_access on public.invoices
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy transactions_project_admin_access on public.transactions
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

create policy payments_project_admin_access on public.payments
  for all to authenticated
  using (
    private.can_manage_project((select i.project_id from public.invoices i where i.id = payments.invoice_id))
  )
  with check (
    private.can_manage_project((select i.project_id from public.invoices i where i.id = payments.invoice_id))
  );

grant select on public.companies, public.profiles to authenticated;
grant select, insert, update, delete on public.projects, public.owners, public.cost_categories,
  public.vendors, public.invoices, public.transactions, public.payments,
  public.project_members, public.project_invitations to authenticated;
grant select, insert, delete on public.admin_allowlist to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on public.admin_allowlist, public.profiles, public.project_members, public.project_invitations from anon;
