create table if not exists public.project_checks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  check_number text not null check (length(trim(check_number)) > 0),
  payee text not null check (length(trim(payee)) > 0),
  amount numeric(12,2) not null check (amount > 0),
  check_date date not null,
  memo text not null default '',
  account_label text not null default 'Bank of America',
  status text not null default 'draft' check (status in ('draft', 'printed', 'voided')),
  printed_at timestamptz,
  voided_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, check_number)
);

create index if not exists project_checks_project_date_idx
  on public.project_checks (project_id, check_date desc, id desc);

alter table public.project_checks enable row level security;

drop policy if exists project_checks_project_admin_access on public.project_checks;
create policy project_checks_project_admin_access on public.project_checks
  for all to authenticated
  using (private.can_manage_project(project_id))
  with check (private.can_manage_project(project_id));

grant select, insert, update on public.project_checks to authenticated;
revoke all on public.project_checks from anon;
